---
variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive

stages:
- lint
- test
- build
- dist
- package
- deploy

cache:
  paths:
    - .cargo
    - target

clippy:
  stage: lint
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

rustfmt check:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

test 0/3:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose --all-targets

test 1/3:
  stage: test
  image: rust:latest
  script:
    - rustup install beta
    - cargo +beta test --verbose --all-targets

test 2/3:
  stage: test
  image: rust:latest
  allow_failure: true
  script:
    - rustup install nightly
    - cargo +nightly test --verbose --all-targets

build:
  stage: build
  image: rust:latest
  script:
    - cargo build --release

dist:
  stage: dist
  image: rust:latest
  script:
    - command cargo-vendor -v || cargo install cargo-vendor
    # or if that doesn't work
    # curl -fsSL https://github.com/alexcrichton/cargo-vendor/releases/download/0.1.23/cargo-vendor-0.1.23-x86_64-unknown-linux-musl.tar.gz | tar -xz --directory="${HOME}/.cargo/bin" --strip-components=1 --wildcards */cargo-vendor
    - export PATH="${PATH}:${HOME}/.cargo/bin"
    - autoreconf -si
    - ./configure
    - make dist
    - make distcheck
  artifacts:
    paths:
    - hubauth-*.tar.xz

deb:
  stage: package
  image: rust:latest
  script: 'true'

artifacts:
  stage: deploy
  image: rust:latest
  script: 'true'
