---
variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive

stages:
- lint
- test
- package
- deploy

cache:
  paths:
    - .cargo
    - target

clippy:
  stage: lint
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

rustfmt check:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

stable:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose --all-targets

beta:
  stage: test
  image: rust:latest
  script:
    - rustup install beta
    - cargo +beta test --verbose --all-targets

nightly:
  stage: test
  image: rust:latest
  allow_failure: true
  script:
    - rustup install nightly
    - cargo +nightly test --verbose --all-targets

tarball:
  stage: package
  image: rust:latest
  script: 'true'

artifacts:
  stage: deploy
  image: rust:latest
  script: 'true'
