#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CMD="$1"
shift

case "$CMD" in
  init)
    cargo run -- "$CMD" "$@"
    ;;
  *)
    cargo run -- "$CMD" --config="${DIR}/misc/hubauth.dev.yml" "$@"
    ;;
esac
