Document: hubauth
Title: Debian hubauth Manual
Author: <insert document author here>
Abstract: This manual describes what hubauth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hubauth/hubauth.sgml.gz

Format: postscript
Files: /usr/share/doc/hubauth/hubauth.ps.gz

Format: text
Files: /usr/share/doc/hubauth/hubauth.text.gz

Format: HTML
Index: /usr/share/doc/hubauth/html/index.html
Files: /usr/share/doc/hubauth/html/*.html
