#!/usr/bin/env bash

set -eu

# docker rust: apt update && apt install ruby ruby-dev groff; gem install ronn-ng

if ! command -v "ronn" >/dev/null
then
  echo -e 'ronn-ng is required:\n  gem install ronn-ng'
  exit 1
fi

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
RELEASE_DOC_DIR="${ROOT_DIR}/target/release/doc"
MAN_DIR="${ROOT_DIR}/doc"

mkdir -p "$RELEASE_DOC_DIR"
cd "$MAN_DIR"

ronn --manual="hubauth" --organization="Liam Dawson" --date="$(date +%Y-%m-%d)" -o "$RELEASE_DOC_DIR" -r5 *.ronn

cd ".."
cp "${MAN_DIR}/hubauth.yml.example" "${RELEASE_DOC_DIR}/"
cp README.md "${RELEASE_DOC_DIR}/readme"
cp CHANGELOG.md "${RELEASE_DOC_DIR}/changelog"
