#!/usr/bin/env bash

set -eu

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

cd "${ROOT_DIR}/target/release"
tar -czf "${ROOT_DIR}/release/hubauth-${1}-linux.tgz" hubauth doc/*
