#!/usr/bin/env bash

set -eu

if command -v adduser >/dev/null; then
  adduser --quiet --system --no-create-home hubauth
else
  getent group hubauth >/dev/null || groupadd -r hubauth
  getent passwd hubauth >/dev/null || useradd -r -g hubauth -d /var/cache/hubauth -s /sbin/nologin -c "Runs hubauth and handles key caching" hubauth
fi
